// menu.js - Contiene i dati del menù per il ristorante

// Dati del menù per ogni giorno della settimana, con pranzo e cena diversi.
// Puoi espandere questo oggetto per includere più giorni e più piatti.
export const menuData = {
    "Mercoledì": {
        "cena": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€5.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Bruschette al Pomodoro",
                price: "€5.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Bruschette+al+Pomodoro"
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Pasta al Ragù di Turgia",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/B22222/FFFFFF?font=open-sans?text=Pasta+al+Ragù\\ndi+Turgia",
            },
            {
                name: "Pasta alla Ligure",
                price: "€7.00",
                labels: ["Vegano"],
                description: "CON PESTO VEGANO CEREALTERRA",
                image: "https://placehold.co/400x150/2E8B57/FFFFFF?font=open-sans?text=Pasta+alla\\nLigure",
            },
            {
                name: "Insalata di Riso Basmati Integrale",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFFFE0/000000?font=open-sans?text=Insalata+di+Riso\\nBasmati+Integrale", //TODO: Controlla il nome
            },
            {
                name: "Hamburger di Carne con Patate",
                price: "€10.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/8B4513/FFFFFF?font=open-sans?text=Hamburger+di+Carne\\ncon+Patate",
            },
            {
                name: "Roast Beef",
                price: "€8.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/D2691E/FFFFFF?font=open-sans?text=Roast+Beef",
            },
            {
                name: "Polpettone di Lenticchie e Melanzane",
                price: "€8.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Polpettone\\ndi+Lenticchie\\ne+Melanzane",
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate al Forno",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Patate+al+Forno",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ]
    },
    "Giovedì": {
        "pranzo": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€6.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Pasta al Ragù di Turgia",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/B22222/FFFFFF?font=open-sans?text=Pasta+al+Ragù\\ndi+Turgia",
            },
            {
                name: "Insalata di Riso Basmati Integrale",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFFFE0/000000?font=open-sans?text=Insalata+di+Riso\\nBasmati+Integrale",
            },
            {
                name: "Roast Beef",
                price: "€8.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/D2691E/FFFFFF?font=open-sans?text=Roast+Beef",
            },
            {
                name: "Polpettone di Lenticchie e Melanzane",
                price: "€8.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Polpettone\\ndi+Lenticchie\\ne+Melanzane",
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate al Forno",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Patate+al+Forno",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ],
        "cena": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€5.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Bruschette al Pomodoro",
                price: "€5.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Bruschette+al+Pomodoro"
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Pasta al Ragù di Turgia",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/B22222/FFFFFF?font=open-sans?text=Pasta+al+Ragù\\ndi+Turgia",
            },
            {
                name: "Pasta alla Ligure",
                price: "€7.00",
                labels: ["Vegano"],
                description: "CON PESTO VEGANO CEREALTERRA",
                image: "https://placehold.co/400x150/2E8B57/FFFFFF?font=open-sans?text=Pasta+alla\\nLigure",
            },
            {
                name: "Insalata di Riso Basmati Integrale",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFFFE0/000000?font=open-sans?text=Insalata+di+Riso\\nBasmati+Integrale",
            },
            {
                name: "Milanese con Patatine",
                price: "€10.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/FFD700/000000?font=open-sans?text=Milanese\\ncon+Patatine",
            },
            {
                name: "Roast Beef",
                price: "€8.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/D2691E/FFFFFF?font=open-sans?text=Roast+Beef",
            },
            {
                name: "Hamburger Vegano con Patatine",
                price: "€10.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/9ACD32/FFFFFF?font=open-sans?text=Hamburger+Vegano",
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate al Forno",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Patate+al+Forno",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ]
    },
    "Venerdì": {
        "pranzo": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€5.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Pasta al Ragù di Turgia",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/B22222/FFFFFF?font=open-sans?text=Pasta+al+Ragù\\ndi+Turgia",
            },
            {
                name: "Insalata di Riso Basmati Integrale",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFFFE0/000000?font=open-sans?text=Insalata+di+Riso\\nBasmati+Integrale",
            },
            {
                name: "Roast Beef",
                price: "€8.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/D2691E/FFFFFF?font=open-sans?text=Roast+Beef",
            },
            {
                name: "Polpettone di Lenticchie e Melanzane",
                price: "€8.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Polpettone\\ndi+Lenticchie\\ne+Melanzane",
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate al Forno",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Patate+al+Forno",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ],
        "cena": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€5.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Bruschette al Pomodoro",
                price: "€5.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Bruschette+al+Pomodoro"
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Pasta all'Amatriciana",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Pasta+all'Amatriciana",
            },
            {
                name: "Pasta alla Norma",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/6A0DAD/FFFFFF?font=open-sans?text=Pasta+alla+Norma", //8A2BE2
            },
            {
                name: "Cous Cous di Mais con Verdure",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFD700/000000?font=open-sans?text=Cous+Cous+di+Mais\\ncon+Verdure",
            },
            {
                name: "Hamburger di Carne con Patatine",
                price: "€10.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/8B4513/FFFFFF?font=open-sans?text=Hamburger+di+Carne\\ncon+Patatine",
            },
            {
                name: "Roast Beef",
                price: "€8.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/D2691E/FFFFFF?font=open-sans?text=Roast+Beef",
            },
            {
                name: "Hamburger Vegano con Patatine",
                price: "€10.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/9ACD32/FFFFFF?font=open-sans?text=Hamburger+Vegano",
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate al Forno",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Patate+al+Forno",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ]
    },
    "Sabato": {
        "pranzo": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€5.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Pasta alla Norma",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/6A0DAD/FFFFFF?font=open-sans?text=Pasta+alla+Norma", //8A2BE2
            },
            {
                name: "Riso Saltato con Verdure",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Riso+Saltato\\ncon+Verdure",
            },
            {
                name: "Hamburger di Carne con Patatine",
                price: "€10.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/8B4513/FFFFFF?font=open-sans?text=Hamburger+di+Carne\\ncon+Patatine",
            },
            {
                name: "Hamburger Vegano con Patatine",
                price: "€10.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/9ACD32/FFFFFF?font=open-sans?text=Hamburger+Vegano\\ncon+Patatine",
            },
            {
                name: "Roast Beef",
                price: "€8.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/D2691E/FFFFFF?font=open-sans?text=Roast+Beef",
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate al Forno",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Patate+al+Forno",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ],
        "cena": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€5.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Bruschette al Pomodoro",
                price: "€5.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Bruschette+al+Pomodoro"
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Pasta all'Amatriciana",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Pasta+all'Amatriciana",
            },
            {
                name: "Agnolotti Burro e Salvia",
                price: "€8.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Agnolotti+Burro\\ne+Salvia",
            },
            {
                name: "Cous Cous di Mais con Verdure",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFD700/000000?font=open-sans?text=Cous+Cous+di+Mais\\ncon+Verdure",
            },
            {
                name: "Grigliata Mista di Carne",
                price: "€11.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A52A2A/FFFFFF?font=open-sans?text=Grigliata+Mista\\ndi+Carne",
            },
            {
                name: "Insalata di Pollo e Verdure",
                price: "€8.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/3CB371/FFFFFF?font=open-sans?text=Insalata+di+Pollo\\ne+Verdure",
            },
            {
                name: "Hamburger Vegano con Patatine",
                price: "€10.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/9ACD32/FFFFFF?font=open-sans?text=Hamburger+Vegano\\ncon+Patatine",
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate Fritte",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFD700/000000?font=open-sans?text=Patate+Fritte",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ]
    },
    "Domenica": {
        "pranzo": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€5.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Agnolotti Burro e Salvia",
                price: "€8.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Agnolotti+Burro\\ne+Salvia",
            },
            {
                name: "Cous Cous di Mais con Verdure",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFD700/000000?font=open-sans?text=Cous+Cous+di+Mais\\ncon+Verdure",
            },
            {
                name: "Riso Saltato con Verdure",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Riso+Saltato\\ncon+Verdure",
            },
            {
                name: "Milanese con Patate",
                price: "€10.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/FFD700/000000?font=open-sans?text=Milanese\\ncon+Patate",
            },
            {
                name: "Roast Beef",
                price: "€8.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/D2691E/FFFFFF?font=open-sans?text=Roast+Beef",
            },
            {
                name: "Polpettone di Verdure e Ceci",
                price: "€8.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Polpettone+di\\nVerdure+e+Ceci",
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate al Forno",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Patate+al+Forno",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ],
        "cena": [
            {
                name: "Tagliere di salumi",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Tagliere+di+Salumi"
            },
            {
                name: "Tagliere di formaggi",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFFACD/000000?font=open-sans?text=Tagliere+di+Formaggi"
            },
            {
                name: "Tagliere di salumi e formaggi",
                price: "€8.00",
                labels: [],
                description: "AZIENDE CAMPAGNA AMICA - Azienda Agricola L'arte del Latte e Società agricola La Carolina",
                image: "https://placehold.co/400x150/DEB887/000000?font=open-sans?text=Tagliere+di+salumi\\ne+formaggi"
            },
            {
                name: "Hummus Mediterraneo con Verdure",
                price: "€6.00",
                labels: ["Vegano", "Gluten Free"],
                description: "CON CECI, CAPPERI E POMODORI SECCHI CEREALTERRA",
                image: "https://placehold.co/400x150/F5DEB3/000000?font=open-sans?text=Hummus+Mediterraneo\\ncon+Verdure",
            },
            {
                name: "Tomini Verdi e Rossi",
                price: "€5.00",
                labels: ["Vegetariano", "Gluten Free"],
                description: "CON BAGNETTO PIEMONTESE E BAGNETTO ROSSO CEREAL TERRA",
                image: "https://placehold.co/400x150/8FBC8F/FFFFFF?font=open-sans?text=Tomini+Verdi\\ne+Rossi",
            },
            {
                name: "Bruschette al Pomodoro",
                price: "€5.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Bruschette+al+Pomodoro"
            },
            {
                name: "Prosciutto e Melone",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/FFA07A/FFFFFF?font=open-sans?text=Prosciutto\\ne+Melone",
            },
            {
                name: "Pasta al Ragù di Turgia",
                price: "€7.00",
                labels: [],
                description: "AZIENDA CAMPAGNA AMICA - Società agricola La Carolina",
                image: "https://placehold.co/400x150/B22222/FFFFFF?font=open-sans?text=Pasta+al+Ragù\\ndi+Turgia",
            },
            {
                name: "Pasta alla Norma",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/6A0DAD/FFFFFF?font=open-sans?text=Pasta+alla+Norma", //8A2BE2
            },
            {
                name: "Cous Cous di Mais con Verdure",
                price: "€7.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FFD700/000000?font=open-sans?text=Cous+Cous+di+Mais\\ncon+Verdure",
            },
            {
                name: "Milanese con Patatine",
                price: "€10.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/FFD700/000000?font=open-sans?text=Milanese\\ncon+Patatine",
            },
            {
                name: "Insalata di Pollo e Verdure",
                price: "€8.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/3CB371/FFFFFF?font=open-sans?text=Insalata+di+Pollo\\ne+Verdure",
            },
            {
                name: "Polpettone di Lenticchie e Verdure",
                price: "€8.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/A0522D/FFFFFF?font=open-sans?text=Polpettone\\ndi+Lenticchie\\ne+Verdure",  //TODO: Controllare usabilità!
            },
            {
                name: "Caprese",
                price: "€7.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/DC143C/FFFFFF?font=open-sans?text=Caprese",
            },
            {
                name: "Patate al Forno",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/DAA520/FFFFFF?font=open-sans?text=Patate+al+Forno",
            },
            {
                name: "Insalata Ricca",
                price: "€7.00",
                labels: [],
                description: "",
                image: "https://placehold.co/400x150/32CD32/FFFFFF?font=open-sans?text=Insalata+Ricca",
            },
            {
                name: "Insalata Verde",
                price: "€4.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/90EE90/000000?font=open-sans?text=Insalata+Verde",
            },
            {
                name: "Anguria",
                price: "€3.00",
                labels: ["Vegano", "Gluten Free"],
                description: "",
                image: "https://placehold.co/400x150/FF6347/FFFFFF?font=open-sans?text=Anguria",
            },
            {
                name: "Panna Cotta",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/FFFAF0/000000?font=open-sans?text=Panna+Cotta",
            },
            {
                name: "Bunet",
                price: "€4.00",
                labels: ["Vegetariano"],
                description: "",
                image: "https://placehold.co/400x150/654321/FFFFFF?font=open-sans?text=Bunet",
            },
            {
                name: "Gelato",
                price: "€3.50",
                labels: ["Vegetariano"],
                description: "AZIENDA CAMPAGNA AMICA - Azienda Agricola L'arte del Latte",
                image: "https://placehold.co/400x150/FFC0CB/000000?font=open-sans?text=Gelato",
            },
        ]
    },
};
